export const jobs = [
  {
    id: 1,
    company: "Photosnap",
    logo: "assets/photosnap.svg",
    new: true,
    featured: true,
    position: "Senior Frontend Developer",
    role: "Frontend",
    level: "Senior",
    postedAt: "1d ago",
    contract: "Full Time",
    location: "USA Only",
    languages: ["HTML", "CSS", "JavaScript"],
    tools: [],
    jobTags: ["Frontend", "Senior", "HTML", "CSS", "JavaScript"],
  },
  {
    id: 2,
    company: "Manage",
    logo: "assets/manage.svg",
    new: true,
    featured: true,
    position: "Fullstack Developer",
    role: "Fullstack",
    level: "Midweight",
    postedAt: "1d ago",
    contract: "Part Time",
    location: "Remote",
    languages: ["Python"],
    tools: ["React"],
    jobTags: ["FullStack", "Midweight", "Python", "React"],
  },
  {
    id: 3,
    company: "Account",
    logo: "assets/account.svg",
    new: true,
    featured: false,
    position: "Junior Frontend Developer",
    role: "Frontend",
    level: "Junior",
    postedAt: "2d ago",
    contract: "Part Time",
    location: "USA Only",
    languages: ["JavaScript"],
    tools: ["React", "Sass"],
    jobTags: ["Frontend", "Junior", "React", "Sass", "JavaScript"],
  },
  {
    id: 4,
    company: "MyHome",
    logo: "assets/myhome.svg",
    new: false,
    featured: false,
    position: "Junior Frontend Developer",
    role: "Frontend",
    level: "Junior",
    postedAt: "5d ago",
    contract: "Contract",
    location: "USA Only",
    languages: ["CSS", "JavaScript"],
    tools: [],
    jobTags: ["Frontend", "Junior", "CSS", "JavaScript"],
  },
  {
    id: 5,
    company: "Loop Studios",
    logo: "assets/loop-studios.svg",
    new: false,
    featured: false,
    position: "Software Engineer",
    role: "Fullstack",
    level: "Midweight",
    postedAt: "1w ago",
    contract: "Full Time",
    location: "Worldwide",
    languages: ["JavaScript", "Ruby"],
    tools: ["Sass"],
    jobTags: ["FullStack", "Midweight", "JavaScript", "Sass", "Ruby"],
  },
  {
    id: 6,
    company: "FaceIt",
    logo: "assets/faceit.svg",
    new: false,
    featured: false,
    position: "Junior Backend Developer",
    role: "Backend",
    level: "Junior",
    postedAt: "2w ago",
    contract: "Full Time",
    location: "UK Only",
    languages: ["Ruby"],
    tools: ["RoR"],
    jobTags: ["Backend", "Junior", "Ruby", "RoR"],
  },
  {
    id: 7,
    company: "Shortly",
    logo: "assets/shortly.svg",
    new: false,
    featured: false,
    position: "Junior Developer",
    role: "Frontend",
    level: "Junior",
    postedAt: "2w ago",
    contract: "Full Time",
    location: "Worldwide",
    languages: ["HTML", "JavaScript"],
    tools: ["Sass"],
    jobTags: ["Frontend", "Junior", "HTML", "Sass", "JavaScript"],
  },
  {
    id: 8,
    company: "Insure",
    logo: "assets/insure.svg",
    new: false,
    featured: false,
    position: "Junior Frontend Developer",
    role: "Frontend",
    level: "Junior",
    postedAt: "2w ago",
    contract: "Full Time",
    location: "USA Only",
    languages: ["JavaScript"],
    tools: ["Vue", "Sass"],
    jobTags: ["Frontend", "Junior", "Vue", "JavaScript", "Sass"],
  },
  {
    id: 9,
    company: "Eyecam Co.",
    logo: "assets/eyecam-co.svg",
    new: false,
    featured: false,
    position: "Full Stack Engineer",
    role: "Fullstack",
    level: "Midweight",
    postedAt: "3w ago",
    contract: "Full Time",
    location: "Worldwide",
    languages: ["JavaScript", "Python"],
    tools: ["Django"],
    jobTags: ["FullStack", "Midweight", "JavaScript", "Django", "Python"],
  },
  {
    id: 10,
    company: "The Air Filter Company",
    logo: "assets/the-air-filter-company.svg",
    new: false,
    featured: false,
    position: "Front-end Dev",
    role: "Frontend",
    level: "Junior",
    postedAt: "1mo ago",
    contract: "Part Time",
    location: "Worldwide",
    languages: ["JavaScript"],
    tools: ["React", "Sass"],
    jobTags: ["Frontend", "Junior", "React", "Sass", "JavaScript"],
  },
];

